version: '2'
services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: always
    ports:
      - "1884:1884"
      - "9001:9001"
    volumes: 
      - ./docker/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

  influxdb:
    image: influxdb:1.8.4
    container_name: influxdb
    restart: always
    volumes:
      - ./docker/influx/data:/var/lib/influxdb
    ports: 
      - "8086:8086"
    environment:
      - INFLUXDB_DB=sensors
      - INFLUXDB_USER=telegraf
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin

  telegraf:
    image: telegraf
    container_name: telegraf
    restart: always
    volumes:
      - ./docker/telegraf/config/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
      - mosquitto
    links:
      - mosquitto
      - influxdb

  grafana: 
    image: grafana/grafana
    container_name: grafana
    depends_on:
      - influxdb
    restart: always
    volumes:
      - ./docker/grafana/data/grafana:/var/lib/grafana
    ports:
      - "3000:3000"
